# Homework Week 5


##### Due September 25th

### 1. Broadcasting

In [6]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([79,89,99])


#### a. Replace each column of arr1 by arr2

In [9]:
arr1[:] = arr2[:,np.newaxis]
print(arr1)

[[79 79 79]
 [89 89 89]
 [99 99 99]]


#### b. Replace each row of arr1 by arr2

In [13]:
arr1[:] = arr2[np.newaxis,:]
print(arr1)

[[79 89 99]
 [79 89 99]
 [79 89 99]]


#### c. Replaces only the 2nd and 3rd column of arr by arr2

In [22]:
arr1[:,1:] = arr2[:,np.newaxis]
print(arr1)

[[ 1 79 79]
 [ 4 89 89]
 [ 7 99 99]]


### 2. Repeating Array Elements

In [26]:
a = np.arange(10,60,10)

##### part 1 
* use ``np.tile`` to repeat this array 5 times
* use ``reshape`` to convert this array into a 2d matrix. With the ``Reshape`` command use
i) the length of a
ii) -1 to do the reshaping instead of hardcoding the dimensions
* take the determinant of this matrix and report the result

In [47]:
b = np.tile(a,5)
print(b)

[10 20 30 40 50 10 20 30 40 50 10 20 30 40 50 10 20 30 40 50 10 20 30 40
 50]


In [69]:
c = np.reshape(np.tile(a,5),(len(a),-1))
print(c)

[[10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]]


In [71]:
d = np.linalg.det(np.reshape(np.tile(a,5),(len(a),-1)))
print("The determinant of the matrix is {}".format(d))

The determinant of the matrix is 0.0


#### part 2
* now take the determinant of the matrix

In [78]:
a = np.array([[1,2.333,-4],[-4,-3,-0.001],[-.2,5.3,9.99]])
print("The determinant of the matrix is {}".format(np.linalg.det(a)))

The determinant of the matrix is 150.46244660000002


#### part 3
* now flatten the arrray in part 2
* use ``np.tile`` to repeat this array 9 times and follow the steps in part 1 to compute the determinant

In [83]:
aflat = a.flatten()
print(aflat)
print('')
d = np.linalg.det(np.reshape(np.tile(aflat,9),(len(aflat),-1)))
print("The determinant of the matrix is {}".format(d))

[ 1.000e+00  2.333e+00 -4.000e+00 -4.000e+00 -3.000e+00 -1.000e-03
 -2.000e-01  5.300e+00  9.990e+00]

The determinant of the matrix is 0.0


### 3. Solving a system of linear equations
Consider this system of linear equations :

8$a_{o}$ + 6$a_{1}$ - 10$a_{2}$ = 2

-4$a_{o}$ - 8$a_{1}$ + 10$a_{2}$ = 5

16$a_{o}$ + 16$a_{1}$  = -3

* Solve this system of equations with i) ``np.linalg.solve`` and ii) ``np.linalg.inv`` + ``np.dot``

* Verify that the values for $a_{o}$, $a_{1}$, and $a_{2}$ provide an exact solution (hint: verify that the lefthand side of the equation yields the righthand side).


In [94]:
a = np.array([[8,6,-10],[-4,-8,10],[16,16,0]])
print(a)
b = np.array([2,5,-3])
print(b)
x = np.linalg.solve(a,b)
print(x)

print(np.dot(a,x))

[[  8   6 -10]
 [ -4  -8  10]
 [ 16  16   0]]
[ 2  5 -3]
[ 1.10416667 -1.29166667 -0.09166667]
[ 2.  5. -3.]


In [92]:
np.allclose(np.dot(a,x),b)

True

In [108]:
y = np.linalg.inv(a)
z = np.dot(y,b)
print(z)

[ 1.10416667 -1.29166667 -0.09166667]


### 4. Performing SVD

Consider the matrix ...

np.array([[1,2,3],[4,5,6],[7,8,9]])

* What happens when you try to invert this matrix directly?  Why? How could you have determined this outcome ahead of time?

* Use SVD to decompose this matrix.  Based on the singular values, where should you truncate $\Sigma$ (i.e. which ``rcond`` value)?

* Given $\Sigma$ what is the "effective" rank of the (decomposed) matrix?



In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])