# Homework Week 5


##### Due September 25th

### 1. Broadcasting

In [20]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([79,89,99])


#### a. Replace each column of arr1 by arr2

In [9]:
arr1[:] = arr2[:,np.newaxis]
print(arr1)

[[79 79 79]
 [89 89 89]
 [99 99 99]]


#### b. Replace each row of arr1 by arr2

In [13]:
arr1[:] = arr2[np.newaxis,:]
print(arr1)

[[79 89 99]
 [79 89 99]
 [79 89 99]]


#### c. Replaces only the 2nd and 3rd column of arr by arr2

In [22]:
arr1[:,1:] = arr2[:,np.newaxis]
print(arr1)

[[ 1 79 79]
 [ 4 89 89]
 [ 7 99 99]]
