# Homework Week 5


##### Due September 25th

### 1. Broadcasting

In [6]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([79,89,99])


#### a. Replace each column of arr1 by arr2

In [9]:
arr1[:] = arr2[:,np.newaxis]
print(arr1)

[[79 79 79]
 [89 89 89]
 [99 99 99]]


#### b. Replace each row of arr1 by arr2

In [13]:
arr1[:] = arr2[np.newaxis,:]
print(arr1)

[[79 89 99]
 [79 89 99]
 [79 89 99]]


#### c. Replaces only the 2nd and 3rd column of arr by arr2

In [22]:
arr1[:,1:] = arr2[:,np.newaxis]
print(arr1)

[[ 1 79 79]
 [ 4 89 89]
 [ 7 99 99]]


### 2. Repeating Array Elements

In [26]:
a = np.arange(10,60,10)

##### part 1 
* use ``np.tile`` to repeat this array 5 times
* use ``reshape`` to convert this array into a 2d matrix. With the ``Reshape`` command use
i) the length of a
ii) -1 to do the reshaping instead of hardcoding the dimensions
* take the determinant of this matrix and report the result

In [47]:
b = np.tile(a,5)
print(b)

[10 20 30 40 50 10 20 30 40 50 10 20 30 40 50 10 20 30 40 50 10 20 30 40
 50]


In [69]:
c = np.reshape(np.tile(a,5),(len(a),-1))
print(c)

[[10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]
 [10 20 30 40 50]]


In [71]:
d = np.linalg.det(np.reshape(np.tile(a,5),(len(a),-1)))
print("The determinant of the matrix is {}".format(d))

The determinant of the matrix is 0.0


#### part 2
* now take the determinant of the matrix

In [78]:
a = np.array([[1,2.333,-4],[-4,-3,-0.001],[-.2,5.3,9.99]])
print("The determinant of the matrix is {}".format(np.linalg.det(a)))

The determinant of the matrix is 150.46244660000002


#### part 3
* now flatten the arrray in part 2
* use ``np.tile`` to repeat this array 9 times and follow the steps in part 1 to compute the determinant

In [83]:
aflat = a.flatten()
print(aflat)
print('')
d = np.linalg.det(np.reshape(np.tile(aflat,9),(len(aflat),-1)))
print("The determinant of the matrix is {}".format(d))

[ 1.000e+00  2.333e+00 -4.000e+00 -4.000e+00 -3.000e+00 -1.000e-03
 -2.000e-01  5.300e+00  9.990e+00]

The determinant of the matrix is 0.0


### 3. Solving a system of linear equations
Consider this system of linear equations :

8$a_{o}$ + 6$a_{1}$ - 10$a_{2}$ = 2

-4$a_{o}$ - 8$a_{1}$ + 10$a_{2}$ = 5

16$a_{o}$ + 16$a_{1}$  = -3

* Solve this system of equations with i) ``np.linalg.solve`` and ii) ``np.linalg.inv`` + ``np.dot``

* Verify that the values for $a_{o}$, $a_{1}$, and $a_{2}$ provide an exact solution (hint: verify that the lefthand side of the equation yields the righthand side).


In [94]:
a = np.array([[8,6,-10],[-4,-8,10],[16,16,0]])
print(a)
b = np.array([2,5,-3])
print(b)
x = np.linalg.solve(a,b)
print(x)

print(np.dot(a,x))

[[  8   6 -10]
 [ -4  -8  10]
 [ 16  16   0]]
[ 2  5 -3]
[ 1.10416667 -1.29166667 -0.09166667]
[ 2.  5. -3.]


In [92]:
np.allclose(np.dot(a,x),b)

True

In [108]:
y = np.linalg.inv(a)
z = np.dot(y,b)
print(z)

[ 1.10416667 -1.29166667 -0.09166667]


### 4. Performing SVD

Consider the matrix ...

np.array([[1,2,3],[4,5,6],[7,8,9]])

* What happens when you try to invert this matrix directly?  Why? How could you have determined this outcome ahead of time?

* Use SVD to decompose this matrix.  Based on the singular values, where should you truncate $\Sigma$ (i.e. which ``rcond`` value)?

* Given $\Sigma$ what is the "effective" rank of the (decomposed) matrix?



In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [7]:
np.linalg.det(a)

-9.51619735392994e-16

In [73]:
u,s,vt = np.linalg.svd(a)

In [75]:
rcond = np.asarray(1e-15)
acon = a.conjugate()

In [77]:
cutoff = rcond[...,np.newaxis] * np.amax(s, axis=-1)

In [79]:
large = s>cutoff

s = np.divide(1, s, where=large, out=s)
s[~large] = 0

In [81]:
s

array([0.05935386, 0.93600574, 0.        ])

In [83]:
s_v2 = s[...,np.newaxis]

In [85]:
right_matrix = np.multiply(s_v2, np.transpose(u))

In [87]:
a_inv2 = np.matmul(vt.T, right_matrix)

In [89]:
a_inv2

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02, -9.89600165e-17,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

In [91]:
np.linalg.pinv(a)

array([[-6.38888889e-01, -1.66666667e-01,  3.05555556e-01],
       [-5.55555556e-02, -9.89600165e-17,  5.55555556e-02],
       [ 5.27777778e-01,  1.66666667e-01, -1.94444444e-01]])

### 5. Truncated SVD

Go back to the 91x91 matrix filled with random numbers.  

* Regenerate this matrix as ``aaa=np.random.rand(91,91)``
* Compute the rank of this matrix
* Re-compute the rank of this matrix if you first decompose it by SVD, truncate terms in $\Sigma$ with ``rcond < 1e-2`` and then re-compose it.
* Compute the variance treating the original matrix aaa as $\bar{x}$ and the re-composed matrix as $x$ and flattening both matrices into 1-D vectors.


In [111]:
import numpy as np
aaa = np.random.rand(91,91)

In [113]:
rank = np.linalg.matrix_rank(aaa)
print(rank)

91


In [117]:
new = np.asarray(aaa)

u,s,vt = np.linalg.svd(new)
S = np.zeros(np.shape(new))
np.fill_diagonal(S,s)

print(S)

rcond = np.asarray(1e-2)
cutoff = rcond[...,np.newaxis] * np.amax(s, axis=-1,keepdims=True)
large = s > cutoff
s = np.divide(1,s,where=large,out=s)
s[~large] = 0

sv2 = s[...,np.newaxis]
ri_mat = np.multiply(sv2, np.transpose(u))
aaa_inv2 = np.matmul(vt.T, ri_mat)

rank2 = np.linalg.matrix_rank(aaa_inv2, tol=1e-2)
print(rank2)

[[4.55593859e+01 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.22378933e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.02556581e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.24768554e-01
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  8.15541742e-02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.77955776e-02]]
82


In [115]:
diff = aaa_inv2.flatten() - aaa.flatten()
var = np.sum(diff**2)/len(diff)
print(var)

0.3359501540363237
