# Homework Week 4 
#### due September 18

### 1. Sequence Function (in-class)

In [12]:
episode = ['Eegah', 'Deathstalker', 'Space Mutiny']
line = ['Watch out for Snakes', "He's Batman", "Big McLarge Huge"]
season = [5,7,8]
biglist = list(zip(episode, line, season))
for i in range(len(biglist)):
    print("Best line of the episode {} in season {} was {}".format(biglist[i][0], biglist[i][2], biglist[i][1]))

Best line of the episode Eegah in season 5 was Watch out for Snakes
Best line of the episode Deathstalker in season 7 was He's Batman
Best line of the episode Space Mutiny in season 8 was Big McLarge Huge


### 2. Sequence Function

Consider the example shown in the data struct part 3 notes of the list comprehension for four stars wth different names HIP 99770, AF Lep, HR 8799, Vega.. It used zip to advance each element of starname, spectype, starmag, and dstar

Now, add the use of enumerate to write a for-loop printing out the number of the star in the list and an indexed version ofabsmag at each interation and then print the full array of absmag outside of the for-loop. 

In [6]:
import numpy as np
starname=['HIP 99770','AF Lep','HR 8799','Vega']
spectype=['A5V','F8V','F0V','A0V']
starmag=np.array([4.9,6.3,5.9,0.0])
dstar=np.array([40.74,26.8, 39.4, 7.7])


ab = []
for h,(i,j,k,l) in enumerate(zip(starname,spectype,starmag,dstar)):
    absmag=k-5*np.log10(l/10.)
    print('The absolute magnitude of star number {0} with name {1:s} with spectral type {2} is {3:.3f}'.format(h+1,i,j,absmag))
    ab.append(absmag)

print(np.array(ab))

The absolute magnitude of star number 1 with name HIP 99770 with spectral type A5V is 1.850
The absolute magnitude of star number 2 with name AF Lep with spectral type F8V is 4.159
The absolute magnitude of star number 3 with name HR 8799 with spectral type F0V is 2.923
The absolute magnitude of star number 4 with name Vega with spectral type A0V is 0.568
[1.84989488 4.15932603 2.92251889 0.56754637]


### 3. List Comprehensions

Write a list comprehension returning a variable vals2 which equals [6,9] (i.e. vals[1] and vals[3] each times 3) using the value of 1/x versus 1/x$^{2}$ for each element x of vals as the conditional.

In [1]:
vals = [.1,2,.4,3]
vals2 = [v*3 for v in vals if v**(-1) > v**(-2)]
print(vals2)


[6, 9]


### 4. Numpy Array Creation

In [6]:
import numpy as np
multi_array = np.random.random((3,4))
print(multi_array)
multi_array2 = np.copy(multi_array)
print(multi_array2)
multi_array2[:,0] = np.ones((1,3))
print(multi_array2)

[[0.53599956 0.19672642 0.65466546 0.14118316]
 [0.04147821 0.88612304 0.41347895 0.34254211]
 [0.51900458 0.97562745 0.30693178 0.30181008]]
[[0.53599956 0.19672642 0.65466546 0.14118316]
 [0.04147821 0.88612304 0.41347895 0.34254211]
 [0.51900458 0.97562745 0.30693178 0.30181008]]
[[1.         0.19672642 0.65466546 0.14118316]
 [1.         0.88612304 0.41347895 0.34254211]
 [1.         0.97562745 0.30693178 0.30181008]]


### 5. Numpy Slicing with Boolean Indexing

In [7]:
import numpy as np
arr = np.loadtxt('spectrum_oct17_adi.dat')
arr[:,2] = np.where(arr[:,3]>5, arr[:,2], -9)
np.savetxt('new_spectrum.txt', arr)

### 6. Array Reshaping (in class)

### 7. Missing Data

In [2]:
import numpy as np
