# Homework Week 5


##### Due September 25th

### 1. Broadcasting

In [1]:
import numpy as np

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([79,89,99])


#### a. Replace each column of arr1 by arr2

In [6]:
arr1[:,0] = arr2
print(arr1)


[[79  2  3]
 [89  5  6]
 [99  8  9]]


#### b. Replace each row of arr1 by arr2

In [ ]:
arr1[:] = arr2
